# Rustfmt configuration for Streamline
# See: https://rust-lang.github.io/rustfmt/

# Maximum line width
max_width = 100

# Use field init shorthand where possible: Foo { x } instead of Foo { x: x }
use_field_init_shorthand = true

# Imports formatting
imports_granularity = "Crate"
